name: Publish packages

run-name: Publish @lena-inc packages from ${{ github.ref_name }}

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  publish:
    uses: Utilities-Studio/infra/.github/workflows/npm-publish.yml@9609ba74b576fe3eee32fa2ac5394ab750b240c4
